config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'reparacions#index'

  get 'tecnicos/perfil', as: 'user_root'

  resources :ordenes, only: [:index, :show]

  resources :reparacions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reparacion.rb
class Reparacion < ApplicationRecord
  # we can specify prefix, no need when using with 'dbo.' 
  self.table_name_prefix = 'dbo.' 
  # specify table name if it breaks Rails conventions
  self.table_name  = 'CCREPARA'
  # specify primary key name if it's other than id
  #self.primary_key = 'ID'

  belongs_to :taller
  belongs_to :user

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  validates :foto, attachment_presence: true

end

app/models/resoption.rb
class Resoption < ApplicationRecord
  # we can specify prefix, no need when using with 'dbo.' 
  self.table_name_prefix = 'dbo.' 
  # specify table name if it breaks Rails conventions
  self.table_name  = 'CCRESOPT'
  # specify primary key name if it's other than id
  #self.primary_key = 'ID'	
end

app/models/taller.rb
class Taller < ApplicationRecord
  # we can specify prefix, no need when using with 'dbo.' 
  self.table_name_prefix = 'dbo.' 
  # specify table name if it breaks Rails conventions
  self.table_name  = 'CCTALLER'
  # specify primary key name if it's other than id
  self.primary_key = 'ID'

  belongs_to :user
  has_many :reparacions
end

app/models/user.rb
class User < ApplicationRecord
  # we can specify prefix, no need when using with 'dbo.' 
  self.table_name_prefix = 'dbo.' 
  # specify table name if it breaks Rails conventions
  self.table_name  = 'USUARIOS'
  # specify primary key name if it's other than id
  #self.primary_key = 'ID'

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :registerable

  has_many :reparacions
  has_many :tallers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    #current_user_path
    root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    request.referrer
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update) { |u|
      u.permit(:password, :password_confirmation, :current_password)
    }
  end
end

app/controllers/ordenes_controller.rb
class OrdenesController < ApplicationController
  before_action :authenticate_user!

  def index

  end

  def show

  end
end

app/controllers/reparacions_controller.rb
class ReparacionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_reparacion, only: [:show, :edit, :update, :destroy]


  # GET /reparacions
  # GET /reparacions.json
  def index
    @reparacions = current_user.reparacions
  end

  # GET /reparacions/1
  # GET /reparacions/1.json
  def show
  end

  # GET /reparacions/new
  def new
    @reparacion = Reparacion.new
  end

  # GET /reparacions/1/edit
  def edit
  end

  # POST /reparacions
  # POST /reparacions.json
  def create
    @reparacion = Reparacion.new(reparacion_params)

    respond_to do |format|
      if @reparacion.save
        format.html { redirect_to @reparacion, notice: 'Reparacion was successfully created.' }
        format.json { render :show, status: :created, location: @reparacion }
      else
        format.html { render :new }
        format.json { render json: @reparacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reparacions/1
  # PATCH/PUT /reparacions/1.json
  def update
    respond_to do |format|
      if @reparacion.update(reparacion_params)
        format.html { redirect_to @reparacion, notice: 'reparacion was successfully updated.' }
        format.json { render :show, status: :ok, location: @reparacion }
      else
        format.html { render :edit }
        format.json { render json: @reparacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reparacions/1
  # DELETE /reparacions/1.json
  def destroy
    @reparacion.destroy
    respond_to do |format|
      format.html { redirect_to reparacions_url, notice: 'reparacion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_reparacion
    @reparacion = Reparacion.find(params[:id])
  end

  def reparacion_params
    accessible = [ :sector, :equipo, :observaciones, :obs_reparacion, :resolucion, :taller_id, :user_id, :sql_ccrepara_norden ]
    # Agregado para Paperclip
    accessible << [ :foto ]
    #accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
    params.require(:reparacion).permit(accessible)
  end
end

app/controllers/tecnicos_controller.rb
class TecnicosController < ApplicationController
  before_action :authenticate_user!

  def perfil
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
        concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
          concat content_tag(:span, 'Cerrar', class: 'sr-only')
        end)
        concat message
      end)
    end
    nil
  end

  def title(page_title)
    content_for(:title) { page_title }
  end
end

app/helpers/ordenes_helper.rb
module OrdenesHelper
end

app/helpers/reparacions_helper.rb
module ReparacionsHelper
end

app/helpers/tecnicos_helper.rb
module TecnicosHelper
end

app/views/application/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Abrir Menu</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <a class="navbar-brand" href="#">Fuente Natural - Ordenes</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if user_signed_in? %>
      <ul class="nav navbar-nav">
        <li><%= link_to "Bienvenido, #{current_user.nombre}", "#" %></li>

        <li class="active">
          <%= link_to reparacions_path do %>
          <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span> &nbsp; Ordenes Pendientes
          <% end %>
        </li>
      </ul>
      <% end %>

      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li>
          <%= link_to destroy_user_session_path, :method => :delete do %>
          <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> &nbsp; Terminar sessión
          <% end %>
        </li>
      <% else %>
        <li>
          <%= link_to new_user_session_path do %>
          <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> &nbsp; Ingresar
          <% end %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FuenteNaturalOrdenes</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <style type="text/css">
  body { padding-top: 80px !important; }
  </style>


  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body>
<%= render "nav" %>

<div class="container">
<div class="row">
  <div class="col-sm-12">
    <%= flash_messages %>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <%= yield %>
  </div>
</div>

</div> <!-- .containter -->

</body>
</html>

app/views/ordenes/index.html.erb
this is index

app/views/ordenes/show.html.erb
show

app/views/reparacions/_form.html.erb
<%= form_for reparacion, :html => { :class => "form-horizontal", multipart: true } do |f| %>
  <% if reparacion.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(reparacion.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% reparacion.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <fieldset>
    <legend>Agregar reporte:</legend>
    <div class="form-group">
      <%= f.text_area :obs_reparacion, :class => "form-control", :rows => 8 %>
    </div>
  </fieldset>


  <fieldset>
    <legend>Agregar foto:</legend>
    <div class="form-group text-center">
      <label class="btn btn-success btn-lg btn-file">
        <span class="glyphicon glyphicon-picture" aria-hidden="true"></span>
        &nbsp; SACAR FOTO <input type="file" name="reparacion[foto]" id="reparacion_foto" style="display: none;" />
      </label>
    </div>
  </fieldset>



  <%= f.hidden_field :id, :value => reparacion.id %>

  <!-- Form actions -->
  <div class="form-group">
    <div class="col-md-12 text-center">
    <%= f.submit "Enviar Reporte", :class => "btn btn-primary btn-sm" %>
    </div>
  </div>



<% end %>

app/views/reparacions/edit.html.erb
<%= content_tag(:h3, "Por favor, complete su informe", :class => "text-center") %>

<div class="col-sm-10 col-sm-offset-1">
<%= render 'form', reparacion: @reparacion %>
</div>

app/views/reparacions/index.html.erb
<% @reparacions.each do |rep| %>
<div class="panel panel-default">
  <div class="panel-body">

    <div class="row">
      <div class="col-sm-8">
        <%= rep.observaciones %>
      </div>

      <div class="col-sm-4 text-right">
        <%= link_to "Reparar", edit_reparacion_path(rep), :class => "btn btn-danger btn-xs" %>
        <%= link_to "Ver", reparacion_path(rep), :class => "btn btn-primary btn-xs" %>
      </div>
    </div>

  </div>
</div>
<% end %>

app/views/reparacions/new.html.erb
new.html.erb

app/views/reparacions/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">

    <div class="row">
      <div class="col-sm-8">
        <%= @reparacion.observaciones %>
      </div>

      <div class="col-sm-4 text-right">
        <a href="#" class="btn btn-primary btn-xs">VER</a>
      </div>
    </div>

  </div>
</div>

app/views/tecnicos/perfil.html.erb
<h1>Tecnicos#perfil</h1>
<p>Find me in app/views/tecnicos/perfil.html.erb</p>